return {
  enable = true,
  keybinds = {
    options = "t",
    modifier = "lctrl",
    f_reroll = "r",
    a_reroll = "a",
    save_state = "z",
    load_state = "x",
  },
  ar_filters = {
    pack = { "p_spectral_mega_1" },
    pack_id = 16,
    voucher_name = "v_clearance_sale",
    voucher_id = 3,
    tag_name = "tag_double",
    tag_id = 3,
    tag2_name = "tag_investment",
    tag2_id = 9,
    soul_skip = 0,
    inst_observatory = false,
    inst_perkeo = false,
  },
  ar_prefs = {
    spf_id = 8,
    spf_int = 5000,
    face_count = 10,
    suit_ratio_id = 2,
    suit_ratio_percent = "50%",
    suit_ratio_decimal = 0.5,
  },
}
