#![allow(clippy::missing_errors_doc)]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BenchGroup {
    Baseline,
    Tags,
    Vouchers,
    Packs,
    Jokers,
    Souls,
    Deck,
}

impl BenchGroup {
    pub const fn key(self) -> &'static str {
        match self {
            Self::Baseline => "baseline",
            Self::Tags => "tags",
            Self::Vouchers => "vouchers",
            Self::Packs => "packs",
            Self::Jokers => "jokers",
            Self::Souls => "souls",
            Self::Deck => "deck",
        }
    }

    pub const fn label(self) -> &'static str {
        match self {
            Self::Baseline => "baseline",
            Self::Tags => "tags",
            Self::Vouchers => "vouchers",
            Self::Packs => "packs",
            Self::Jokers => "jokers",
            Self::Souls => "souls",
            Self::Deck => "deck",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BenchShape {
    Hit,
    Miss,
    Mixed,
}

impl BenchShape {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Hit => "hit",
            Self::Miss => "miss",
            Self::Mixed => "mixed",
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct BenchCase {
    pub name: &'static str,
    pub group: BenchGroup,
    pub shape: BenchShape,
    pub note: &'static str,
    pub seed_start: &'static str,
    pub voucher: &'static str,
    pub pack: &'static str,
    pub tag1: &'static str,
    pub tag2: &'static str,
    pub joker: &'static str,
    pub joker_location: &'static str,
    pub souls: f64,
    pub observatory: bool,
    pub perkeo: bool,
    pub deck: &'static str,
    pub erratic: bool,
    pub no_faces: bool,
    pub min_face_cards: i32,
    pub suit_ratio: f64,
}

pub fn selected_bench_cases(selected: &str) -> Result<Vec<BenchCase>, String> {
    let mut cases = bench_cases();
    if selected == "all" {
        return Ok(cases);
    }

    cases.retain(|case| case.name == selected || case.group.key() == selected);
    if cases.is_empty() {
        Err(format!(
            "unknown benchmark case or group: {selected}. Use all, {}, or an exact case name.",
            bench_group_keys().join(", ")
        ))
    } else {
        Ok(cases)
    }
}

pub fn bench_group_keys() -> Vec<&'static str> {
    vec![
        BenchGroup::Baseline.key(),
        BenchGroup::Tags.key(),
        BenchGroup::Vouchers.key(),
        BenchGroup::Packs.key(),
        BenchGroup::Jokers.key(),
        BenchGroup::Souls.key(),
        BenchGroup::Deck.key(),
    ]
}

pub fn bench_cases() -> Vec<BenchCase> {
    vec![
        BenchCase {
            name: "baseline-hit",
            group: BenchGroup::Baseline,
            shape: BenchShape::Hit,
            note: "no filters; isolates ABI/result overhead",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "tag-hit",
            group: BenchGroup::Tags,
            shape: BenchShape::Hit,
            note: "single blind tag check with early hit behavior",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "dual-tag",
            group: BenchGroup::Tags,
            shape: BenchShape::Mixed,
            note: "requires both blind tag slots to satisfy filters",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "tag_buffoon",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "voucher-hit",
            group: BenchGroup::Vouchers,
            shape: BenchShape::Hit,
            note: "ante-1 voucher roll",
            seed_start: "",
            voucher: "v_telescope",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "pack-hit",
            group: BenchGroup::Packs,
            shape: BenchShape::Hit,
            note: "two shop pack slots, pack-only filter",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "observatory",
            group: BenchGroup::Packs,
            shape: BenchShape::Mixed,
            note: "voucher plus celestial pack rolls",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: true,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "shop-hit",
            group: BenchGroup::Jokers,
            shape: BenchShape::Hit,
            note: "first-shop joker slots with a normal joker target",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "shop-miss",
            group: BenchGroup::Jokers,
            shape: BenchShape::Miss,
            note: "shop joker search for legendary Perkeo; full-budget miss",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Perkeo",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "pack-joker",
            group: BenchGroup::Jokers,
            shape: BenchShape::Mixed,
            note: "Buffoon pack slots plus pack joker generation",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Reserved Parking",
            joker_location: "pack",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "any-joker",
            group: BenchGroup::Jokers,
            shape: BenchShape::Mixed,
            note: "shop-or-pack joker search with a Buffoon pack filter",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Blueprint",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "pack-miss",
            group: BenchGroup::Souls,
            shape: BenchShape::Miss,
            note: "spectral pack plus impossible Soul count pressure",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_normal_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 3.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "souls-arcana",
            group: BenchGroup::Souls,
            shape: BenchShape::Mixed,
            note: "Arcana pack Soul counting path",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "perkeo",
            group: BenchGroup::Souls,
            shape: BenchShape::Mixed,
            note: "Soul detection followed by legendary pool roll",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "erratic",
            group: BenchGroup::Deck,
            shape: BenchShape::Mixed,
            note: "Erratic Deck opening-card face count",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 12,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "erratic-suit",
            group: BenchGroup::Deck,
            shape: BenchShape::Mixed,
            note: "Erratic Deck suit concentration check",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.8,
        },
    ]
}
